const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/Itxxwasi/WASI-TECH-BOT-V1";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VaDK8ZUDjiOhwFS1cP2j";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VaDK8ZUDjiOhwFS1cP2j" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/733b2d3b5f1d1e1aeec0f.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923192173398" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923192173398";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "true"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOMEWELCOM || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923192173398,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923192173398";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "ＧＥＮＥＲＴＥＤ ＢＹ ＷＡＳＩ 🇵🇰",
 
  author : process.env.PACK_AUTHER|| "ＩＴＸ",
  packname: process.env.PACK_NAME || "ＷＡＳＩ♥️",
  botname : process.env.BOT_NAME  || "𝗪𝗔𝗦𝗜-𝗠𝗗",
  ownername:process.env.OWNER_NAME|| "𝗪𝗔𝗦𝗜",

  sessionName:process.env.SESSION_ID || "SUHAIL_13_20_09_02_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTQ0LFxuICAgICAgICAxMixcbiAgICAgICAgMjQ2LFxuICAgICAgICA2OCxcbiAgICAgICAgMTA3LFxuICAgICAgICAxNTksXG4gICAgICAgIDM5LFxuICAgICAgICA5OSxcbiAgICAgICAgMjIsXG4gICAgICAgIDc5LFxuICAgICAgICAyNDUsXG4gICAgICAgIDgyLFxuICAgICAgICAxNjYsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTc2LFxuICAgICAgICA3MyxcbiAgICAgICAgMTAzLFxuICAgICAgICAxMjcsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTExLFxuICAgICAgICAzNixcbiAgICAgICAgNDksXG4gICAgICAgIDgsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTM5LFxuICAgICAgICA0NixcbiAgICAgICAgMTY5LFxuICAgICAgICA2OCxcbiAgICAgICAgMzAsXG4gICAgICAgIDE0OCxcbiAgICAgICAgOTUsXG4gICAgICAgIDc5XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTg5LFxuICAgICAgICA2LFxuICAgICAgICA0MSxcbiAgICAgICAgMTkzLFxuICAgICAgICAxMyxcbiAgICAgICAgMjksXG4gICAgICAgIDc5LFxuICAgICAgICAyNyxcbiAgICAgICAgMTI1LFxuICAgICAgICAxNzUsXG4gICAgICAgIDI0OCxcbiAgICAgICAgNjksXG4gICAgICAgIDE4MCxcbiAgICAgICAgNzEsXG4gICAgICAgIDIyLFxuICAgICAgICA4MixcbiAgICAgICAgMjE3LFxuICAgICAgICA2NSxcbiAgICAgICAgNTIsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjMyLFxuICAgICAgICA3LFxuICAgICAgICAxMDQsXG4gICAgICAgIDEyLFxuICAgICAgICA3NCxcbiAgICAgICAgMTEyLFxuICAgICAgICAxOSxcbiAgICAgICAgOTEsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxOVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEyLFxuICAgICAgICAxODEsXG4gICAgICAgIDU2LFxuICAgICAgICAxNTMsXG4gICAgICAgIDE4NCxcbiAgICAgICAgODQsXG4gICAgICAgIDk0LFxuICAgICAgICA5OCxcbiAgICAgICAgMTA3LFxuICAgICAgICA1MSxcbiAgICAgICAgMTcwLFxuICAgICAgICA2MyxcbiAgICAgICAgNzEsXG4gICAgICAgIDE4LFxuICAgICAgICAxMCxcbiAgICAgICAgMTcxLFxuICAgICAgICAzMixcbiAgICAgICAgMTEyLFxuICAgICAgICA0MyxcbiAgICAgICAgMTUwLFxuICAgICAgICAxNDUsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTg3LFxuICAgICAgICA5MixcbiAgICAgICAgMjIwLFxuICAgICAgICAxNTIsXG4gICAgICAgIDYxLFxuICAgICAgICAxNjIsXG4gICAgICAgIDM3LFxuICAgICAgICA4NixcbiAgICAgICAgMjE1LFxuICAgICAgICA4NVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNixcbiAgICAgICAgMzEsXG4gICAgICAgIDIxNixcbiAgICAgICAgMzIsXG4gICAgICAgIDYsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMTkxLFxuICAgICAgICAxMTcsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTMsXG4gICAgICAgIDEwLFxuICAgICAgICAxMDEsXG4gICAgICAgIDQxLFxuICAgICAgICA0NyxcbiAgICAgICAgMTg2LFxuICAgICAgICAyNDAsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxMDIsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMjIxLFxuICAgICAgICAyMDksXG4gICAgICAgIDIzNixcbiAgICAgICAgMjI2LFxuICAgICAgICAxNDYsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTc3LFxuICAgICAgICA4MSxcbiAgICAgICAgMjA0LFxuICAgICAgICAxMDksXG4gICAgICAgIDEyNixcbiAgICAgICAgMTI0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjAsXG4gICAgICAgIDYwLFxuICAgICAgICAyMTIsXG4gICAgICAgIDgwLFxuICAgICAgICAxNDgsXG4gICAgICAgIDcwLFxuICAgICAgICAxNDIsXG4gICAgICAgIDIwOCxcbiAgICAgICAgNTEsXG4gICAgICAgIDEsXG4gICAgICAgIDM2LFxuICAgICAgICAyMzgsXG4gICAgICAgIDI4LFxuICAgICAgICAyMyxcbiAgICAgICAgMTAxLFxuICAgICAgICAxNDAsXG4gICAgICAgIDQ4LFxuICAgICAgICAyNTUsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjIwLFxuICAgICAgICAyMSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyMjgsXG4gICAgICAgIDIxMixcbiAgICAgICAgMCxcbiAgICAgICAgMTU0LFxuICAgICAgICAxODEsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTkwLFxuICAgICAgICAxODgsXG4gICAgICAgIDM1LFxuICAgICAgICA3NlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMTUsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTcsXG4gICAgICAgIDE5OCxcbiAgICAgICAgODcsXG4gICAgICAgIDExLFxuICAgICAgICA4MixcbiAgICAgICAgOTEsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTMsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTk0LFxuICAgICAgICA2MCxcbiAgICAgICAgOCxcbiAgICAgICAgMTAzLFxuICAgICAgICAyNDksXG4gICAgICAgIDksXG4gICAgICAgIDEwOSxcbiAgICAgICAgMzUsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTk0LFxuICAgICAgICAxODQsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTY3LFxuICAgICAgICAxLFxuICAgICAgICAxODAsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMTYzLFxuICAgICAgICAyMzcsXG4gICAgICAgIDI1MixcbiAgICAgICAgMTMwLFxuICAgICAgICAyNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICAyMSxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICA2NCxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICA0MixcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDIxMCxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgNzVcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICAxODksXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICA3NyxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgMTYzLFxuICAgICAgICAgIDEsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDExMlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDExLFxuICAgICAgICAwLFxuICAgICAgICAyMjQsXG4gICAgICAgIDExNyxcbiAgICAgICAgMzIsXG4gICAgICAgIDEwLFxuICAgICAgICAxOTIsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjA4LFxuICAgICAgICA3OSxcbiAgICAgICAgNDgsXG4gICAgICAgIDUwLFxuICAgICAgICAxNixcbiAgICAgICAgMjEzLFxuICAgICAgICAxMDAsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTA4LFxuICAgICAgICA1NixcbiAgICAgICAgMjEwLFxuICAgICAgICA1NCxcbiAgICAgICAgMjIzLFxuICAgICAgICAxODEsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTQxLFxuICAgICAgICAxMDYsXG4gICAgICAgIDIyMyxcbiAgICAgICAgNzQsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTQ2LFxuICAgICAgICA5MSxcbiAgICAgICAgNjksXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTc4LFxuICAgICAgICA4NyxcbiAgICAgICAgNDQsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMjIyLFxuICAgICAgICAyNTUsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTgsXG4gICAgICAgIDc2LFxuICAgICAgICA0LFxuICAgICAgICAyNDQsXG4gICAgICAgIDI1LFxuICAgICAgICAyNDgsXG4gICAgICAgIDI5LFxuICAgICAgICAyNDcsXG4gICAgICAgIDY5LFxuICAgICAgICAxMzAsXG4gICAgICAgIDExMSxcbiAgICAgICAgNzgsXG4gICAgICAgIDExNyxcbiAgICAgICAgMzksXG4gICAgICAgIDI1MixcbiAgICAgICAgMjAwLFxuICAgICAgICAxMDgsXG4gICAgICAgIDkyLFxuICAgICAgICAwLFxuICAgICAgICAxNzUsXG4gICAgICAgIDIyNixcbiAgICAgICAgMjM5LFxuICAgICAgICA0LFxuICAgICAgICAxMTIsXG4gICAgICAgIDFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEyNSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJkQkFoWTNxZ2ZSWERaVnNGSTNUWkY1NW9UckNZWTU0d2pPSU03alpUR1ZrPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDkxMjE3ODU2MjdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjE3QzdEODI0QTdFOEVDQ0I0QTlDQjJDNEVBMzE2OUFBXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNTI4MzE5OVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDkxMjE3ODU2MjdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjA4NDQ3Q0YzOUEwNTI1RjVGODIwQTRBMkIxNTFFMDU0XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNTI4MzIwMVxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCIwMjFRYzJ0NVNSLXVoN094TUJ2WkZBXCIsXG4gIFwicGhvbmVJZFwiOiBcIjA1N2Y3ODdlLTYyZjYtNGRlMS1iMWMzLTRiOGQxMmRiOTUzNVwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA4OCxcbiAgICAgIDg1LFxuICAgICAgNTAsXG4gICAgICA0MixcbiAgICAgIDEwNSxcbiAgICAgIDM5LFxuICAgICAgMTIsXG4gICAgICA1OSxcbiAgICAgIDkwLFxuICAgICAgMjI5LFxuICAgICAgNDMsXG4gICAgICAyMzQsXG4gICAgICAxMyxcbiAgICAgIDE4LFxuICAgICAgMjAsXG4gICAgICA5NCxcbiAgICAgIDIwMSxcbiAgICAgIDE4OSxcbiAgICAgIDE2LFxuICAgICAgNzhcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTgyLFxuICAgICAgMTA0LFxuICAgICAgMjE0LFxuICAgICAgMTQ0LFxuICAgICAgMjM1LFxuICAgICAgMTQ2LFxuICAgICAgMjI1LFxuICAgICAgMjM3LFxuICAgICAgOCxcbiAgICAgIDIwNSxcbiAgICAgIDI3LFxuICAgICAgMTE5LFxuICAgICAgMjA0LFxuICAgICAgMTYxLFxuICAgICAgMjAsXG4gICAgICAxNTcsXG4gICAgICAzLFxuICAgICAgMjE5LFxuICAgICAgMTc2LFxuICAgICAgMzJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiUUc4NVA4MUdcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDkxMjE3ODU2Mjc6MjNAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJFTU1ZIFNPTFVUSU9OXCIsXG4gICAgXCJsaWRcIjogXCIxNTE0NTM5MzUxMzY5OTE6MjNAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDS3IzNDRRRUVQYjIxcllHR0JZZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJTWEd0NWNoQnNiRU9hMzMvRnIwM3RtcENLb0lzTnEraldEc0JMQ1ZtdTNRPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIlVtQVAyQVJYUjBjSWNkNytVbjNiZGdsL0k3SzVQR250UEMvTFc1dnFkVTIwcGtnOGhjdGtFcngwUEkxK3FseXNqQ3lJRklQaFZvYmt2NEpDYnRsa0FBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIk9tZ05wWHRCREVyV2Q2cEdoR2lKWm0wSmw4Q2cvaTJUYXBmM24wSU5kYzdsOXFjZTI1Rk5Vd2Y0THgvU2JuTDE4ODZ4c0FzTWNSUlpBYkthMnFubEFBPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDkxMjE3ODU2Mjc6MjNAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICAyMixcbiAgICAgICAgICAxODksXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICA2NixcbiAgICAgICAgICA0MixcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICA1OSxcbiAgICAgICAgICAxLFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTE2XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjUyODMxOTQsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFNYWlcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU1haS5qc29uIjogIntcImtleURhdGFcIjpcIk5vZStrWlRodlk1NnpQWThyTWZSOVNJN0ZoYUt0MWtkUFNzdVExLzExVUk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTA4Mzc2NzcyMSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "RybcWhfzZJ7Wd46dgGE21kLt",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "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",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "25",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "5c804a3fc8fb6ca21eeaecacf9935870",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
